Patilendir/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Patilendir.Models;

namespace Patilendir
{
    public class AnimalsController : Controller
    {
        private PatilendirEntities db = new PatilendirEntities();

        // GET: Animals
        public ActionResult UzgunIndex()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                    return View(db.Animal.ToList());
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }
        public ActionResult GulenIndex()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                    return View(db.Animal.ToList());
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }
    }
}

Patilendir/Controllers/Hay_HakController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Patilendir.Controllers
{
    public class Hay_HakController : Controller
    {
        public ActionResult IndexHay_Hak()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                    return View();
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }
    }
}

Patilendir/Controllers/KurtarilanlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Patilendir.Controllers
{
    public class KurtarilanlarController : Controller
    {
        public ActionResult IndexKrtrlnlr()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                    return View();
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }
    }
}

Patilendir/Views/Shared/Login.cshtml
@{
    ViewBag.Title = Patilendir.Resource.GirişYap;
    Layout = "~/Views/Shared/_Login_Layout.cshtml";
}

<div class="container">
    @if (TempData["LoginResult"] != "")
    {
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6" style=" background-color:#f1f1f1;">@TempData["LoginResult"]</div>
            <div class="col-md-3"></div>
        </div>
    }


    <div class="row">
        <div class="col-md-3 text-center"> <img class="img img-responsive" src="~/Content/Logomakr_3zxoy8.png" /></div>
        <div class="col-md-6">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">@Patilendir.Resource.GirişYap</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">@Patilendir.Resource.ÜyeOl</a>
                        </div>
                    </div>
                    <hr>
                </div>

                <div class="panel-body">

                    <div class="row">
                        <div class="col-lg-6 col-md-6">

                            @using (Html.BeginForm("LoginTry", "LoginRegister", FormMethod.Post))
                            {
                                <form id="login-form" role="form" style="display: block;">
                                    @Html.AntiForgeryToken()

                                    <div class="form-group">
                                        <input type="text" name="email" id="email" tabindex="1" class="form-control" placeholder="E-Mail" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder=@Patilendir.Resource.Şifre>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value=@Patilendir.Resource.GirişYap />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            }
                        </div>
                        <div class="col-lg-6 col-md-6">
                            @using (Html.BeginForm("RegisterTry", "LoginRegister", FormMethod.Post))
                            {

                                <form id="register-form" role="form" style="display: none;">
                                    @Html.AntiForgeryToken()
                                    <div class="form-group">
                                        <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email " value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder=@Patilendir.Resource.Şifre>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="name" id="name" tabindex="1" class="form-control" placeholder=@Patilendir.Resource.ad value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="surname" id="surname" tabindex="2" class="form-control" placeholder=@Patilendir.Resource.Soyad>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value=@Patilendir.Resource.ŞimdiÜyeOl>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Patilendir/Views/Shared/_FooterPartial.cshtml
<link href="~/Content/footer.css" rel="stylesheet" />
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left">@Patilendir.Resource.footerYazı<a href="https://www.facebook.com/ipek.altinok">@@ipekAltinok</a></p>
            <div class="pull-right">
                <ul class="social">
                    <li> <a href="https://www.facebook.com/PetsbookOfficial/?fref=ts" target="_blank"> <i class="fa fa-facebook">   </i> </a> </li>
                    <li> <a href="https://twitter.com/ehayvansahip" target="_blank"> <i class="fa fa-twitter">   </i> </a> </li>
                    <li> <a href="https://www.youtube.com/channel/UCPIvT-zcQl2H0vabdXJGcpg" target="_blank"> <i class="fa fa-youtube">   </i> </a> </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Patilendir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/jquery-3.1.1.js"></script>

    <link href="~/Content/slider.css" rel="stylesheet" />
</head>
<body>

    @Html.Partial("_MenuPartial")

    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_FooterPartial")
    </div>

    <script src="~/Scripts/JS_Arama.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Patilendir/Views/Shared/_Login_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <link href="~/Content/DataTables/css/login.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    @*<link href="Content/dataTables.bootstrap.css" rel="stylesheet" />*@
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_FooterPartial")
    </div> 
</body>
</html>

Patilendir/Views/Shared/_MenuPartial.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img src="~/Content/Logomakr_3zxoy8.png" class="img img-responsive navbar-brand" />
            @Html.ActionLink("Patilendir", "Index", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(@Patilendir.Resource.GülenPatiler, "GulenIndex", "Animals")</li>
                <li>@Html.ActionLink(@Patilendir.Resource.ÜzgünPatiler, "UzgunIndex", "Animals")</li>
                <li>@Html.ActionLink(@Patilendir.Resource.KurtarılanPatiler, "IndexKrtrlnlr", "Kurtarilanlar")</li>
                <li>@Html.ActionLink(@Patilendir.Resource.HayvanHakları, "IndexHay_Hak", "Hay_Hak")</li>
                <li> <a href="@Url.Action("Change", "Home", new { language = "TR" })" class="language" rel="tr-TR">TR</a></li>
                <li> <a href="@Url.Action("Change", "Home", new { language = "EN" })" class="language" rel="en-US">EN</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li>
                        <form action="" class="search-form">
                            <div class="form-group has-feedback">
                                <label for="search" class="sr-only">@Patilendir.Resource.Arama</label>
                                <input type="text" class="form-control" name="search" id="search">
                                <span class="glyphicon glyphicon-search form-control-feedback"></span>
                            </div>
                        </form>
                   
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink(@Patilendir.Resource.Çıkış, "Cikis", "LoginRegister")</li>
            </ul>
        </div>

    </div>
</div>