PatilendirAdminPanel/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatilendirAdminPanel.Models;

namespace PatilendirAdminPanel.Controllers
{
    public class AdminUsersController : Controller
    {
        private PatilendirAdminPanelEntities db = new PatilendirAdminPanelEntities();

        // GET: AdminUsers
        public ActionResult Index()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                {
                    var adminUser = db.AdminUser.Include(a => a.Status);
                    return View(adminUser.ToList());
                }
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }


        // GET: AdminUsers/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminUser adminUser = db.AdminUser.Find(id);
            if (adminUser == null)
            {
                return HttpNotFound();
            }
            return View(adminUser);
        }

        // POST: AdminUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            AdminUser adminUser = db.AdminUser.Find(id);
            db.AdminUser.Remove(adminUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatilendirAdminPanel/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatilendirAdminPanel.Models;
using System.Data.Entity.Core.Objects;

namespace PatilendirAdminPanel.Controllers
{
    public class AnimalsController : Controller
    {
        private PatilendirAdminPanelEntities db = new PatilendirAdminPanelEntities();

        // GET: Animals
        public ActionResult Index()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                {
                    var animal = db.Animal.Include(a => a.AnimalStatus).Include(a => a.AnimalType).Include(a => a.Gender).Include(a => a.Status).Include(a => a.Status1);
                    return View(animal.ToList());
                }
                else
                    return RedirectToAction("Login", "LoginRegister");
            }
        }

        // GET: Animals/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animal.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // GET: Animals/Create
        public ActionResult Create()
        {
            ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name");
            ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name");
            ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name");
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name");
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name");
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AnimalId,StatusId,AnimalStatusId,Name,Description,AnimalTypeId,GenderId,YearAsMonth,ContactName,ContactTelephone,Image,InsertionDate,InsertedUserId,UpdatedDate,UpdatedUserId")] Animal animal)
        
        {
            if (ModelState.IsValid)
            {
                string staticPath = "https://dl.dropboxusercontent.com/u/67477431/imagesPets/";

                ObjectParameter returnCode = new ObjectParameter("returnCode", typeof(Int32));

                db.AddAnimal(animal.Name,animal.AnimalStatusId, animal.Description, animal.AnimalTypeId, animal.GenderId, animal.YearAsMonth, animal.ContactName, animal.ContactTelephone, staticPath + animal.Image, Convert.ToInt64(((System.Data.Entity.Core.Objects.ObjectParameter)HttpContext.Application["AdminUserId"]).Value), returnCode);
               
                if (Convert.ToInt32(returnCode.Value) == 1)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name", animal.AnimalStatusId);
                    ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name", animal.AnimalTypeId);
                    ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name", animal.GenderId);
                    ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
                    ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
                    return View(animal);
                }
            }

            ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name", animal.AnimalStatusId);
            ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name", animal.AnimalTypeId);
            ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name", animal.GenderId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            return View(animal);

        }

        // GET: Animals/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animal.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name", animal.AnimalStatusId);
            ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name", animal.AnimalTypeId);
            ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name", animal.GenderId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AnimalId,StatusId,AnimalStatusId,Name,Description,AnimalTypeId,GenderId,YearAsMonth,ContactName,ContactTelephone,Image,InsertionDate,InsertedUserId,UpdatedDate,UpdatedUserId")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter returnCode = new ObjectParameter("returnCode", typeof(Int32));

                db.UpdateAnimal(animal.AnimalId, animal.AnimalStatusId, animal.Name, animal.Description, animal.AnimalTypeId, animal.GenderId, animal.YearAsMonth, animal.ContactName, animal.ContactTelephone, animal.Image, Convert.ToInt64(((System.Data.Entity.Core.Objects.ObjectParameter)HttpContext.Application["AdminUserId"]).Value), returnCode);

                if (Convert.ToInt32(returnCode.Value) == 1)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name", animal.AnimalStatusId);
                    ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name", animal.AnimalTypeId);
                    ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name", animal.GenderId);
                    ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
                    ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
                    return View(animal);
                }
            }

            ViewBag.AnimalStatusId = new SelectList(db.AnimalStatus, "AnimalStatusId", "Name", animal.AnimalStatusId);
            ViewBag.AnimalTypeId = new SelectList(db.AnimalType, "AnimalTypeId", "Name", animal.AnimalTypeId);
            ViewBag.GenderId = new SelectList(db.Gender, "GenderId", "Name", animal.GenderId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", animal.StatusId);
            return View(animal);
        }

        // GET: Animals/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animal.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Animal animal = db.Animal.Find(id);
            db.Animal.Remove(animal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatilendirAdminPanel/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatilendirAdminPanel.Models;

namespace PatilendirAdminPanel.Controllers
{
    public class CustomersController : Controller
    {
        private PatilendirAdminPanelEntities db = new PatilendirAdminPanelEntities();

        // GET: Customers
        public ActionResult Index()
        {
            if (HttpContext.Application["LoginStatus"] == null)
            {
                return RedirectToAction("Login", "LoginRegister");
            }
            else
            {
                if (HttpContext.Application["LoginStatus"].ToString() == "1")
                {
                    var customer = db.Customer.Include(c => c.Status);
                    return View(customer.ToList());
                }
                else
                    return RedirectToAction("Login", "LoginRegister");
            }           
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatilendirAdminPanel/Views/Shared/Login.cshtml
@{
    ViewBag.Title = PatilendirAdminPanel.Resource.Giriş;
    Layout = "~/Views/Shared/_Login_Layout.cshtml";
}

<div class="container">
    @if (TempData["LoginResult"] != "")
    {
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="background-color:#f1f1f1;">@TempData["LoginResult"]</div>
            <div class="col-md-2"></div>
        </div>
    }

    <div class="row">
        <div class="col-md-3 text-center"> <img class="img img-responsive" src="~/Content/Logomakr_3zxoy8.png" /></div>
        <div class="col-md-7">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#" class="active" id="login-form-link">@PatilendirAdminPanel.Resource.GirişYap</a>
                        </div>
                    </div>
                    <hr>
                </div>

                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-7">
                            @using (Html.BeginForm("LoginTry", "LoginRegister", FormMethod.Post))
                            {
                                <form id="login-form" role="form" style="display: block;">
                                    @Html.AntiForgeryToken()
                                    <div class="form-group">
                                        <input type="text" name="email" id="email" tabindex="1" class="form-control" placeholder="E-Mail" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder=@PatilendirAdminPanel.Resource.Şifre>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value=@PatilendirAdminPanel.Resource.GirişYap />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            }
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

PatilendirAdminPanel/Views/Shared/_FooterPartial.cshtml
<link href="~/Content/footer.css" rel="stylesheet" />
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left">@PatilendirAdminPanel.Resource.footerYazı<a href="https://www.facebook.com/ipek.altinok">@@ipekAltinok</a></p>
            <div class="pull-right">
                <ul class="social">
                    <li> <a href="https://www.facebook.com/PetsbookOfficial/?fref=ts"> <i class=" fa fa-facebook">   </i> </a> </li>
                    <li> <a href="https://twitter.com/ehayvansahip"> <i class="fa fa-twitter">   </i> </a> </li>
                    <li> <a href="https://www.youtube.com/channel/UCPIvT-zcQl2H0vabdXJGcpg"> <i class="fa fa-youtube">   </i> </a> </li>
                </ul>
            </div>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

PatilendirAdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <script src="~/Scripts/jquery-3.1.1.js"></script>

    <link href="~/Content/slider.css" rel="stylesheet" /> @*slider icin*@
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    @*<link href="Content/dataTables.bootstrap.css" rel="stylesheet" />*@
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
</head>
<body>

    @Html.Partial("_MenuPartial")

    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_FooterPartial")
    </div>  
  
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PatilendirAdminPanel/Views/Shared/_Login_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <link href="~/Content/DataTables/css/login.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    @*<link href="Content/dataTables.bootstrap.css" rel="stylesheet" />*@
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_FooterPartial")
    </div> 
</body>
</html>

PatilendirAdminPanel/Views/Shared/_MenuPartial.cshtml
@{
    string currentCulture = System.Threading.Thread.CurrentThread.CurrentUICulture.ToString();
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Patilendir", "Index", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(@PatilendirAdminPanel.Resource.Animals, "Index", "Animals")</li>
                <li>@Html.ActionLink(@PatilendirAdminPanel.Resource.AdminUsers, "Index", "AdminUsers")</li> 
                <li>@Html.ActionLink(@PatilendirAdminPanel.Resource.Customers, "Index", "Customers")</li> 
                <li> <a href="@Url.Action("Change", "Home", new { language = "TR" })" class="language" rel="it-IT">TR</a></li>
                <li> <a href="@Url.Action("Change", "Home", new { language = "EN" })" class="language" rel="en-US">EN</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink(@PatilendirAdminPanel.Resource.Çıkış, "Cikis", "LoginRegister")</li>
            </ul>

        </div>

    </div>
</div>